// Database client and schema. Apps import from "@sendcoop/db" so they never
// talk to Postgres directly.

export { getDb, getSql, pingDatabase, type Db } from "./client";
export * from "./affiliate-networks";
export * from "./bot-detection";
export * from "./custom-fields";
export * from "./destination";
export * from "./postback-params";
export * from "./conversion-api";
export * from "./pixel-params";
export * from "./shopify";
export * from "./woocommerce";
export * from "./postback-templates";
export * from "./domain-verification";
export * from "./imports";
export * from "./secrets";
export * from "./segments";
export * from "./sending-domains";
export * from "./signed-links";
export * from "./schema";
export * from "./queries/ab-tests";
export * from "./queries/attribution";
export * from "./queries/audience";
export * from "./queries/bulk";
export * from "./queries/clicks";
export * from "./queries/conversions";
export * from "./queries/campaigns";
export * from "./queries/custom-fields";
export * from "./queries/domain-verification";
export * from "./queries/feedback";
export * from "./queries/forms";
export * from "./queries/health";
export * from "./queries/import-batch";
export * from "./queries/imports";
export * from "./queries/links";
export * from "./queries/integrations";
export * from "./queries/lists";
export * from "./queries/media";
export * from "./queries/reports";
export * from "./queries/segments";
export * from "./queries/sending-domains";
export * from "./queries/sending-servers";
export * from "./queries/subscribers";
export * from "./queries/suppressions";
export * from "./queries/tags";
export * from "./queries/templates";
export * from "./queries/unsubscribe";
export * from "./queries/workspaces";

export const SERVICE_NAMES = ["web", "worker", "edge"] as const;
export type ServiceName = (typeof SERVICE_NAMES)[number];
